
import React, { useState, useEffect } from 'react';
import { Footer } from '@/shared/ui/Layout/Footer';
import { ScrollAnimatedSection } from '@/shared/ui/Animations/ScrollAnimatedSection';
import { DocumentTextIcon } from '@/shared/ui/Icons/DocumentTextIcon';
import { ArrowDownTrayIcon } from '@/shared/ui/Icons/ArrowDownTrayIcon';
import { ChatBubbleLeftRightIcon } from '@/shared/ui/Icons/ChatBubbleLeftRightIcon';
import { SparklesIcon } from '@/shared/ui/Icons/SparklesIcon';
import { ClockIcon } from '@/shared/ui/Icons/ClockIcon';
import { CheckBadgeIcon } from '@/shared/ui/Icons/CheckBadgeIcon';
import { UserCircleIcon } from '@/shared/ui/Icons/UserCircleIcon';
import { View } from '@/shared/types';
import '@/features/marketing/styles/HomePage.css';

interface PageProps {
    onNavigate: (view: View) => void;
    onBookDemo: () => void;
}

// --- MOCK UI COMPONENTS ---

const MockExecutiveSummary = () => (
    <div className="bg-white rounded-xl shadow-2xl border border-slate-200 overflow-hidden max-w-4xl mx-auto transform transition-all duration-500 hover:scale-[1.01] hover:shadow-primary/10">
        {/* App Header Bar */}
        <div className="bg-slate-50 px-4 py-3 border-b border-slate-200 flex justify-between items-center">
            <div className="flex items-center gap-3">
                <div className="w-8 h-8 bg-white rounded-lg border border-slate-200 flex items-center justify-center text-primary shadow-sm">
                    <DocumentTextIcon className="w-5 h-5" />
                </div>
                <div>
                    <h3 className="text-sm font-bold text-slate-800">Lease Abstract: Tech Park Building A</h3>
                    <p className="text-[10px] text-slate-500">Generated by Penaki AI • 2 mins ago</p>
                </div>
            </div>
            <div className="flex gap-2">
                <button className="p-1.5 hover:bg-white rounded-md text-slate-400 hover:text-primary transition-colors">
                    <ArrowDownTrayIcon className="w-4 h-4" />
                </button>
            </div>
        </div>

        <div className="flex flex-col md:flex-row h-[500px]">
            {/* Sidebar Navigation */}
            <div className="w-48 bg-slate-50 border-r border-slate-200 p-4 hidden md:block">
                <div className="space-y-1">
                    <div className="px-3 py-2 bg-white rounded-lg border border-slate-200 shadow-sm text-xs font-bold text-primary flex justify-between items-center cursor-pointer">
                        <span>Executive Summary</span>
                    </div>
                    <div className="px-3 py-2 text-slate-500 text-xs font-medium hover:bg-slate-100 rounded-lg cursor-pointer">Critical Dates</div>
                    <div className="px-3 py-2 text-slate-500 text-xs font-medium hover:bg-slate-100 rounded-lg cursor-pointer">Financials</div>
                    <div className="px-3 py-2 text-slate-500 text-xs font-medium hover:bg-slate-100 rounded-lg cursor-pointer">Clauses</div>
                </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 p-8 overflow-y-auto bg-white relative">
                {/* AI Badge */}
                <div className="absolute top-6 right-8 flex items-center gap-1.5 px-2.5 py-1 bg-purple-50 text-purple-600 rounded-full border border-purple-100 shadow-sm">
                    <SparklesIcon className="w-3 h-3" />
                    <span className="text-[10px] font-bold uppercase tracking-wider">AI Generated</span>
                </div>

                <div className="space-y-6 max-w-2xl">
                    <div>
                        <h4 className="text-lg font-bold text-slate-800 mb-2 border-b border-slate-100 pb-2">Overview</h4>
                        <p className="text-sm text-slate-600 leading-relaxed">
                            This lease agreement for <strong className="text-slate-900">Tech Park Building A</strong> (Suite 400) commences on <strong className="text-slate-900">January 01, 2024</strong> for a term of 60 months. The Tenant, <strong className="text-slate-900">Innovate Inc.</strong>, is granted one (1) option to renew for an additional 5-year period.
                        </p>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div className="p-3 bg-slate-50 rounded-lg border border-slate-100">
                            <p className="text-[10px] uppercase font-bold text-slate-400 mb-1">Base Rent</p>
                            <p className="text-lg font-bold text-slate-800">$12,500.00 <span className="text-xs font-normal text-slate-500">/mo</span></p>
                        </div>
                        <div className="p-3 bg-slate-50 rounded-lg border border-slate-100">
                            <p className="text-[10px] uppercase font-bold text-slate-400 mb-1">Security Deposit</p>
                            <p className="text-lg font-bold text-slate-800">$25,000.00</p>
                        </div>
                    </div>

                    <div>
                        <h4 className="text-sm font-bold text-slate-800 mb-2 mt-2">Key Obligations</h4>
                        <ul className="space-y-2 text-sm text-slate-600">
                            <li className="flex gap-2">
                                <span className="text-primary mt-1">•</span>
                                <span>Tenant is responsible for direct payment of utilities.</span>
                            </li>
                            <li className="flex gap-2">
                                <span className="text-primary mt-1">•</span>
                                <span>Landlord maintains roof and structural elements.</span>
                            </li>
                            <li className="flex gap-2">
                                <span className="text-primary mt-1">•</span>
                                <span><strong className="text-slate-800">Holdover:</strong> 150% of base rent if Tenant remains past expiration.</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
);

const MockChatInterface = () => {
    const [messages, setMessages] = useState([
        { role: 'user', text: "What is the notice period for the renewal option?" },
        { role: 'ai', text: "According to Section 4.2, the Tenant must provide written notice no earlier than 12 months and no later than 9 months prior to the expiration date." }
    ]);

    return (
        <div className="bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden flex flex-col h-[400px] w-full max-w-md mx-auto relative">
            <div className="bg-gradient-to-r from-indigo-600 to-primary p-4 flex items-center justify-between shadow-md z-10">
                <div className="flex items-center gap-3 text-white">
                    <div className="w-8 h-8 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-md">
                        <SparklesIcon className="w-4 h-4" />
                    </div>
                    <div>
                        <h4 className="font-bold text-sm">Lease Assistant</h4>
                        <p className="text-[10px] text-indigo-100 opacity-90">Online • Connected to Lease #8291</p>
                    </div>
                </div>
            </div>

            <div className="flex-1 bg-slate-50 p-4 space-y-4 overflow-hidden relative">
                {messages.map((msg, i) => (
                    <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-slide-up`} style={{animationDelay: `${i * 0.1}s`}}>
                        <div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm shadow-sm ${
                            msg.role === 'user' 
                            ? 'bg-indigo-600 text-white rounded-tr-none' 
                            : 'bg-white border border-slate-200 text-slate-700 rounded-tl-none'
                        }`}>
                            {msg.text}
                        </div>
                    </div>
                ))}
                
                {/* Floating Typing Indicator */}
                <div className="absolute bottom-4 left-4 bg-white border border-slate-200 px-3 py-2 rounded-full shadow-sm flex items-center gap-1 animate-pulse">
                    <div className="w-1.5 h-1.5 bg-slate-400 rounded-full"></div>
                    <div className="w-1.5 h-1.5 bg-slate-400 rounded-full"></div>
                    <div className="w-1.5 h-1.5 bg-slate-400 rounded-full"></div>
                </div>
            </div>

            <div className="p-3 bg-white border-t border-slate-200">
                <div className="bg-slate-100 rounded-full h-10 px-4 flex items-center text-sm text-slate-400 border border-transparent hover:bg-white hover:border-slate-300 transition-all cursor-text">
                    Ask a follow-up question...
                </div>
            </div>
        </div>
    );
};

export const SolutionLeaseSummaries: React.FC<PageProps> = ({ onNavigate, onBookDemo }) => {
    return (
        <div className="min-h-screen bg-white text-slate-900 font-sans bg-grid-pattern relative">
            {/* Hero Section */}
            <section className="relative pt-16 md:pt-20 pb-24 px-6 overflow-hidden">
                <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-sky-50 rounded-full blur-3xl -mr-32 -mt-32 -z-10"></div>
                <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-indigo-50 rounded-full blur-3xl -ml-24 -mb-24 -z-10"></div>

                <div className="max-w-7xl mx-auto text-center relative z-10">
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-100 text-slate-700 border border-slate-200 text-sm font-bold uppercase tracking-wide mb-8 animate-fade-in hover:bg-white hover:shadow-md transition-all cursor-default">
                        <DocumentTextIcon className="w-5 h-5 text-indigo-600" />
                        Automated Reporting
                    </div>
                    
                    <h1 className="text-5xl md:text-7xl font-black text-slate-900 tracking-tight mb-8 leading-tight animate-slide-up">
                        Clarity in a <br/>
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-sky-500">
                            Single Snapshot
                        </span>
                    </h1>
                    
                    <p className="text-xl text-slate-600 max-w-2xl mx-auto mb-12 leading-relaxed animate-slide-up" style={{animationDelay: '0.1s'}}>
                        Transform 100+ page lease agreements into concise, standardized executive summaries in seconds. 
                        Give your stakeholders the bottom line without the legalese.
                    </p>
                    
                    <div className="flex flex-col sm:flex-row justify-center gap-4 animate-slide-up" style={{animationDelay: '0.2s'}}>
                        <button onClick={onBookDemo} className="px-8 py-4 bg-slate-900 text-white rounded-xl font-bold shadow-xl hover:bg-indigo-600 transition-all transform hover:-translate-y-1">
                            Generate Sample Summary
                        </button>
                    </div>
                </div>
            </section>

            {/* Feature 1: The Summary Visualization */}
            <ScrollAnimatedSection className="py-20 px-6 bg-white bg-grid-pattern">
                <div className="max-w-6xl mx-auto">
                    <div className="text-center mb-16">
                        <h2 className="text-3xl font-black text-slate-900 mb-4">Instant Executive Briefs</h2>
                        <p className="text-lg text-slate-600">
                            Our AI reads the entire document, extracting financials, dates, and critical clauses into a clean, readable format.
                        </p>
                    </div>
                    <MockExecutiveSummary />
                </div>
            </ScrollAnimatedSection>

            {/* Feature 2: Interactive Q&A */}
            <ScrollAnimatedSection className="py-24 bg-slate-50 border-y border-slate-200">
                <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                    <div className="order-2 lg:order-1">
                        <div className="relative group perspective-1000">
                            <div className="absolute -inset-4 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-2xl opacity-20 blur-xl group-hover:opacity-30 transition-opacity duration-700"></div>
                            <div className="transform transition-transform duration-700 hover:rotate-1">
                                <MockChatInterface />
                            </div>
                        </div>
                    </div>
                    <div className="order-1 lg:order-2">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-100 text-purple-700 text-xs font-bold uppercase tracking-wide mb-6">
                            <ChatBubbleLeftRightIcon className="w-4 h-4" /> AI Assistant
                        </div>
                        <h2 className="text-4xl font-black text-slate-900 mb-6">Interrogate Your Documents</h2>
                        <p className="text-lg text-slate-600 mb-8 leading-relaxed">
                            Static summaries are great, but specific questions arise. Use our integrated AI Assistant to ask complex questions about any lease in your portfolio.
                        </p>
                        <ul className="space-y-4">
                            {[
                                'Get instant answers with page-level citations',
                                'Clarify ambiguous clauses like "Force Majeure" or "Holdover"',
                                'Compare terms against your standard templates'
                            ].map((item, i) => (
                                <li key={i} className="flex items-center gap-3 text-slate-700 font-medium">
                                    <div className="w-6 h-6 rounded-full bg-green-100 flex items-center justify-center text-green-600 flex-shrink-0">
                                        <CheckBadgeIcon className="w-4 h-4" />
                                    </div>
                                    {item}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </ScrollAnimatedSection>

            {/* Feature 3: Speed & Efficiency Cards */}
            <ScrollAnimatedSection className="py-24 px-6 bg-white bg-grid-pattern">
                <div className="max-w-7xl mx-auto">
                    <div className="text-center mb-16">
                        <h2 className="text-3xl font-black text-slate-900">Accelerate Your Workflow</h2>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                        <div className="p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:shadow-xl hover:border-indigo-100 transition-all group">
                            <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center shadow-sm text-indigo-600 mb-6 text-2xl font-bold border border-slate-100 group-hover:scale-110 transition-transform">
                                <ClockIcon className="w-7 h-7" />
                            </div>
                            <h3 className="text-xl font-bold text-slate-900 mb-3">90% Faster Review</h3>
                            <p className="text-slate-600 leading-relaxed">
                                Cut abstracting time from hours to minutes. Focus your team on high-value analysis instead of data entry.
                            </p>
                        </div>
                        <div className="p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:shadow-xl hover:border-sky-100 transition-all group">
                            <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center shadow-sm text-sky-600 mb-6 text-2xl font-bold border border-slate-100 group-hover:scale-110 transition-transform">
                                <UserCircleIcon className="w-7 h-7" />
                            </div>
                            <h3 className="text-xl font-bold text-slate-900 mb-3">Stakeholder Ready</h3>
                            <p className="text-slate-600 leading-relaxed">
                                Export clean, branded PDF or Excel summaries instantly. Perfect for sharing with investors, legal, or management.
                            </p>
                        </div>
                        <div className="p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:shadow-xl hover:border-purple-100 transition-all group">
                            <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center shadow-sm text-purple-600 mb-6 text-2xl font-bold border border-slate-100 group-hover:scale-110 transition-transform">
                                <SparklesIcon className="w-7 h-7" />
                            </div>
                            <h3 className="text-xl font-bold text-slate-900 mb-3">Always Accurate</h3>
                            <p className="text-slate-600 leading-relaxed">
                                Our Human-in-the-Loop verification option ensures 100% data integrity for your most critical assets.
                            </p>
                        </div>
                    </div>
                </div>
            </ScrollAnimatedSection>

            {/* Final CTA */}
            <ScrollAnimatedSection className="py-24 bg-slate-900 text-white text-center px-6">
                <h2 className="text-3xl sm:text-4xl font-black mb-8">Stop reading, start analyzing.</h2>
                <div className="flex flex-col sm:flex-row justify-center gap-4">
                    <button onClick={onBookDemo} className="px-10 py-4 bg-indigo-600 text-white rounded-xl font-bold shadow-xl hover:bg-indigo-500 transition-all transform hover:-translate-y-1">
                        Book a Demo
                    </button>
                    <button onClick={() => onNavigate('abstract')} className="px-10 py-4 bg-transparent border border-slate-600 text-slate-300 rounded-xl font-bold hover:bg-white/10 transition-all hover:text-white">
                        Try It Yourself
                    </button>
                </div>
            </ScrollAnimatedSection>

            <Footer onNavigate={onNavigate} />
        </div>
    );
};
